// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyConCN0P-EQyWTeLT6oxJYNT9qKkmLudc8',
    appId: '1:760979832619:web:d9c2015c209332f47a8f6e',
    messagingSenderId: '760979832619',
    projectId: 'scjr1-mobile-final',
    authDomain: 'scjr1-mobile-final.firebaseapp.com',
    storageBucket: 'scjr1-mobile-final.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQ62jpjc7xuDpmpMm3EQOV2gc9cPrqInY',
    appId: '1:760979832619:android:b5048045b2d453957a8f6e',
    messagingSenderId: '760979832619',
    projectId: 'scjr1-mobile-final',
    storageBucket: 'scjr1-mobile-final.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD1tC5rPHevXMdCKRpjpof34xQy9agshU',
    appId: '1:760979832619:ios:6814f8a8a250a8f27a8f6e',
    messagingSenderId: '760979832619',
    projectId: 'scjr1-mobile-final',
    storageBucket: 'scjr1-mobile-final.appspot.com',
    iosClientId: '760979832619-2behh8jlkllmkj2chhkr988a5m91j02s.apps.googleusercontent.com',
    iosBundleId: 'br.com.fiap.scjr1ProjetoFinalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD1tC5rPHevXMdCKRpjpof34xQy9agshU',
    appId: '1:760979832619:ios:6814f8a8a250a8f27a8f6e',
    messagingSenderId: '760979832619',
    projectId: 'scjr1-mobile-final',
    storageBucket: 'scjr1-mobile-final.appspot.com',
    iosClientId: '760979832619-2behh8jlkllmkj2chhkr988a5m91j02s.apps.googleusercontent.com',
    iosBundleId: 'br.com.fiap.scjr1ProjetoFinalMobile',
  );
}
