// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEQI6RyIGGvYyKesvY3qFQBu10yqH2p5Q',
    appId: '1:440218767357:web:19df535164e5b0befcd394',
    messagingSenderId: '440218767357',
    projectId: 'scjr1-final-mobile',
    authDomain: 'scjr1-final-mobile.firebaseapp.com',
    storageBucket: 'scjr1-final-mobile.appspot.com',
    measurementId: 'G-FX5FPDWZMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7GZfz3hw3YC_wSxob3OQi69ZVAa5a6qU',
    appId: '1:440218767357:android:d42e8a0d2904aa42fcd394',
    messagingSenderId: '440218767357',
    projectId: 'scjr1-final-mobile',
    storageBucket: 'scjr1-final-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD11pQ8lkLQ5ZN9WwsGkKpPboc06e6jznM',
    appId: '1:440218767357:ios:2308fb293ba36082fcd394',
    messagingSenderId: '440218767357',
    projectId: 'scjr1-final-mobile',
    storageBucket: 'scjr1-final-mobile.appspot.com',
    iosClientId: '440218767357-gkkinegp7jui3417nu7idsj7qcu5ctet.apps.googleusercontent.com',
    iosBundleId: 'br.com.fiap.scjr1ProjetoFinalMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD11pQ8lkLQ5ZN9WwsGkKpPboc06e6jznM',
    appId: '1:440218767357:ios:2308fb293ba36082fcd394',
    messagingSenderId: '440218767357',
    projectId: 'scjr1-final-mobile',
    storageBucket: 'scjr1-final-mobile.appspot.com',
    iosClientId: '440218767357-gkkinegp7jui3417nu7idsj7qcu5ctet.apps.googleusercontent.com',
    iosBundleId: 'br.com.fiap.scjr1ProjetoFinalMobile',
  );
}
